# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Getting started'
prompts:
  - 'Output valid JSON with numbers from {{start}} - {{end}}. Do not include any additional text.'

providers:
  - ollama:llama2
  - ollama:granite3.2

tests:
  - vars:
      start: 1
      end: 9
    assert:
      - type: contains-all
        value:
         - 1
         - 2
         - 3
         - 4
         - 5
         - 6
         - 7
         - 8
         - 9
      - type: is-json
  - vars:
      start: 97
      end: 105
    assert:
      - type: contains-all
        value:
         - 97
         - 98
         - 99
         - 100
         - 101
         - 102
         - 103
         - 104
         - 105
      - type: is-json
